apiVersion: v1
kind: Service
metadata:
    labels:
        app: nginx
    name: nginx-service
    namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
